"""Portal check-in and task reward rules."""

CHECK_IN_COINS = 50
PLUS_CHECK_IN_BONUS_DIAMONDS = 5
PREMIUM_CHECK_IN_BONUS_COINS = 50
PREMIUM_CHECK_IN_BONUS_DIAMONDS = 10
STREAK_TOTAL_COINS = 200
STREAK_DIAMONDS = 1
STREAK_DAYS = 7
DAILY_TASK_COINS = 10
MONTHLY_TASK_DIAMONDS = 10
GAME_MODE_DAILY_1 = "chessmater"
GAME_MODE_DAILY_2 = "chess-tourmaster"
GAME_MODE_MONTHLY = "chess-tourmaster"
MONTHLY_TARGET = 20
